spring.application.name=EMS
security.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS
security.jwt.expiration-minutes=120

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=davit.beridze.2003@gmail.com
spring.mail.password=owig qwcu vaal lyif
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8

app.mail.from=davit.beridze.2003@gmail.com